### ISSUE TITLE
1.19?

### ISSUE THREAD

**Issue by Mafy-17** [MelbyBaldove/SKS-fabric-mods#3]
1.19 versiopn for tl_skin_cape_fabric ?

**Comment by lxsmnsyc** [comment]
Not yet, we need every other mods to be 1.19 compatible

**Comment by TheoryOfNekomata** [comment]
@Wayturns That's a client mod provided by TLauncher; it is not provided elsewhere. If you're running TLauncher with a 1.19 instance of Fabric, you should be able to acquire it.

This repo is only for inventory on our private server.

**Comment by Mafy-17** [comment]
> 

I was hoping for a version on official launcher as tlauncher is kinda glitched for official mc users rn
